name: project11
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  flutter_inappwebview: ^5.7.2+3
  http: ^1.1.0
  firebase_messaging: ^14.2.2
  firebase_remote_config:
  firebase_core: ^2.1.1
  flutter_local_notifications: ^9.8.0+1
  overlay_support: ^2.1.0
  firebase_analytics: ^10.6.3
  in_app_review: ^2.0.6
  share_plus:
  intl: ^0.19.0
  hive: ^2.2.3
  appsflyer_sdk: 
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  flutter_slidable: ^3.1.1
  app_tracking_transparency: ^2.0.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: SFR
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
    - family: SF
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
    - family: SFB
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf